### ISSUE TITLE
Proxy collectivizer commands

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#684]
- allow whitelisted users like PandaMaster to send commands to MarvinTMB, who can distribute them to intended bots

**Comment by pieterbrandsen** [comment]
Check whitelisted users .. segment every ... (10) ticks, if found command then execute it. Only apply to console commands

**Comment by pieterbrandsen** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/90001913-b7e6-4ce9-9c72-82bf9d04e64e)
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/2b147977-3078-41dd-90c8-6e4531fda5ce)

First 0 is terrainCoords, which is wrong. Maybe harvest positons are not set correctly

**Comment by DefaultO** [comment]
> * allow whitelisted users like PandaMaster to send commands to MarvinTMB, who can distribute them to intended bots

I like that. Optional: make it ask whitelisted users if an action should get executed when the action comes from Marvin himself. Marvin could turn evil at any point or become biased towards someone (the unforgotten past is proof of that - something was done that the others didn't agree with). It is way harder to get hated by every single member of the Round Table. And if that is the case, then whatever should get executed on that someone's end is probably deserved.

> ![image](https://user-images.githubusercontent.com/45623682/269074444-90001913-b7e6-4ce9-9c72-82bf9d04e64e.png) ![image](https://user-images.githubusercontent.com/45623682/269074462-2b147977-3078-41dd-90c8-6e4531fda5ce.png)
> 
> First 0 is terrainCoords, which is wrong. Maybe harvest positons are not set correctly

~~Did you look where it breaks? I assume it is still that baseCoords one (``if (this.baseCoords[packedCoord] !== 255) continue``). At least I believe it was that when I tried to debug this before (drawing and outputting the possible positions at each stage). This was around the time I asked Marvin how to check/visualize that baseCoords array (because of that annoying compression he does on all memory objects). So I can see what blocks the tile (can only be a road, container, extension, or link, in theory). I think he didn't help me and told me he would look at it himself.~~

Ah, I see. So it should have those 4 positions after filtering out the invalid ones.
Could it be that this is missing a ``[i]``? https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab/src/room/communePlanner.ts#L961
I guess it only matters if the path has to be valid (like in memory). Because we are pushing towards ``sourceHarvestPositions[i]``:
https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab/src/room/communePlanner.ts#L975C17-L975C23

**Comment by pieterbrandsen** [comment]
I am moving the second conversation to #697  as my screenshots should have went there :)

**Comment by pieterbrandsen** [comment]
I agree, or atleast lets limit what commands can be executed, maybe set in the settings and base it on an level or just list of.


Marvin tried to kill you indeed via a push, I guess normally it should be fine but lets set some options on what can be executed.
I think we should have an innerAlly array who can execute commands to another.


Voting system is an good idea, atleast 1 for basic commands, 2 for special ones, 3 for dangerous ones.
Default, dont forget that an attack or claim command can already trigger an attack out of enemy line maybe so lets indeed create some system for this.

**Comment by pieterbrandsen** [comment]
(the deleted comment is unrelated to this ticket)
