### ISSUE TITLE
communePlanner base encoding error

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#698]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/9cbc0a96-e1e0-4215-9c02-8803a0c9a31d)

- happened after fixing source harvest position construction problem
- encoding / decoding bug? Seems like wrong data was submitted, perhaps an empty value

Presently I don't need any help on this issue. Thanks

**Comment by pieterbrandsen** [comment]
We can close this, reset your base plans. If you check out the commit history you will see I changed this file. That was because I noticed that baseplans were filled single and then it couldn't be split by ,

This means that sometimes you would get an entire base plan in 1 string which was decoded as an single one
