### ISSUE TITLE
Inaccessible upgrade pos

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#742]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/0e800c18-21d0-4eff-8b77-525fefb61147)

**Comment by DefaultO** [comment]
Not much you can do here. There simply is no room there for a lot of creeps to upgrade. But I would prefer 2 upgraders in exchange for the Link/Container to get placed next to (or on) the furthest possible position to still reach the Controller.

My bot logic thinks this would be the proper way to handle this spot:
-> Get all possible upgrader positions (<4), and put the container on a tile inside the rectangle by determining the furthest tile by linear distance to the controller, while also preferring the one that is closest to the base. For links, it has to be outside the rectangle (since you can't stand on a link), but it works the same way.

![Unbenannt-1](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/42414542/2a92355f-5dc0-4e4d-a0d8-dd1c1091f79b)

How about reserving spots around the controller (<4 tiles around it), and minerals (<1-2) for creeps only? Preventing the base planner from blocking paths or anything like that.

This shows that your logic is way too complex for what it really is. In regards to base planning. I saw it fail a lot of times for sources/minerals inside the base too. It would not be able to place a link or the extensions to fill, because that would have blocked the path to the source. Not sure if you changed that, but this used to push the harvesters around when a hauler came by. Or they were stationary and started blocking other creeps because the paths crossed with the harvest position.
