### ISSUE TITLE
Remote combat

### ISSUE THREAD

**Issue by realacesu** [CarsonBurke/The-Internationale-Screeps-Bot#764]
**DISSCUSSION NEEDED!**

> This feature requires a subset of additions/changes for this to be implemented effectively.

Currently we do not fight for remotes. We hope to use "Dynamic Squads" for this feature once its complete.
Defending of our remotes seems okay for now. But remote takeovers could be implemented too. That will most likely require moderation if this an auto behavior, as this could bully new players near to us in combination with 'autoAttack' which attacks player rooms. 

### _Requirements for full implementation_ 

- [ ] Dynamic Squads (#729)

### _Some problems Remote Defense will solve_

- More stable economy from remotes.

### _Additions discussed to be needed so far_

- New combatRequest types related to remote combat

--- 

> Implementation to be further discussed and added to this description later.

**Comment by CarsonBurke** [comment]
I think we need to figure out the specifics of spawning, remote interaction and request assignment. 

At what point do we spawn a dynamic squad instead of a single defender? At what point do we spawn multiple dynamic squads? How do we ensure they work together (imagine 3 dynamic squads entering a contested remote one at a time and all dying to an enemy that they could have beaten if they worked together). 

Then with request assignment: can squads respond to multiple remote defence requests at once? If so, how do we ensure the best distribution of them? For example, if enemies keep showing up in 2 remotes and a dynamic squad is trying to defend both, how do we accurately determine that we need more creeps to defend both rooms?

Remote interactions: how do we determine a remote is safe for continued harvesting? How do we determine access to a remote is safe based on what remote defence requests are fulfilled?

I'm not expecting you to have answers, ad I don't either. But if there are points you want to deconstruct, please do and we can discuss/plan in detial
